
model:
  Encoder: DUL-S18
  Dulbrn: 32
  Decoder: ATTMIX
  Head: Mixhead
  ckpt:
    caformer_m36: /data/users/liyachuan/ckpt/caformer_m36_384_in21ft1k.pth
    caformer_s18: /data/users/liyachuan/ckpt/caformer_s18_384_in21ft1k.pth
    vgg16: /data/users/liyachuan/ckpt/vgg16.pth
  loss: ELBO #UNCERT WCE
  FeatDrop: True


dataset:
  ColorJitter: True
  RandomGray: True
  GaussianBlur: True
  GaussianNoise: True
  NMS: True
  Rotate: True
  Flip: True
  CutMix: True
  label_method: randm   #

  BSDS:
    root: /data/users/liyachuan/dataset/BSDS-yc
    loss_lmbda: 1.1

  BIPED:
    root: /data/users/liyachuan/dataset/BIPED
    loss_lmbda: 1.1

  BSDS-PASCAL:
    root: /data/users/liyachuan/dataset
    loss_lmbda: 1.1

  NYUD:
    root: /data/users/liyachuan/dataset/NYUD
    loss_lmbda: 1.3

  SemiBSDS10:
    root: /data/users/liyachuan/dataset/BSDS-yc
    ldata: train_BSDS_10.lst
    udata: ulabeledpascal.lst
    test: test.lst
    loss_lmbda: 1.1
    thrs: 0.9 # binrary the persudo label
    crop_size:
      - 480
      - 320
    nsample: 10103


  SemiBSDS:
    root: /data/users/liyachuan/dataset/BSDS-yc
    ldata: train_BSDS.lst
    udata: ulabeledpascal.lst
    test: test.lst
    loss_lmbda: 1.1
    thrs: 0.9 # binrary the persudo label
    crop_size:
      - 480
      - 320

  SemiNYUD:
    root: /data/users/liyachuan/dataset/NYUD
    ldata: image-train12.lst # replace 0.5 scale by 1.2 scale
    udata: SUNRGBD/unlabled-rgb.lst
    test: image-test.lst
    loss_lmbda: 1.3
    thrs: 0.9 # binrary the persudo label
    crop_size:
      - 400
      - 400

  SemiBIPED:
    root: /data/users/liyachuan/dataset/BIPED
    ldata: train_pair.lst
    udata: udata.lst
    test: test.lst
    loss_lmbda: 1.1
    thrs: 0.9 # binrary the persudo label
    crop_size:
      - 380
      - 380



